### ISSUE TITLE
Старшему разработчику: Обзор библиотек лексического разбора (lexer)

### ISSUE THREAD

**Issue by the-vindicar** [Students-of-the-city-of-Kostroma/16PIa#1]
Напоминаю, что лексер преобразует входную строку в последовательность элементов - токенов. Например:
Входная строка: x = 2 + 35
Выходные токены: идентификатор "x", символ "=", число "2", символ "+", число "35", конец строки.

Необходимо: 
1. выбрать факторы сравнения (лицензия, системные требования, качество документации, активность обновлений/поддержки, простота использования на основании примеров и т.п.).
2. найти несколько альтернатив, решающих данную задачу.
3. составить сводку сравнения в виде таблицы фактор\альтернатива.

**Comment by the-vindicar** [comment]
[Пишем простой лексер на регулярных выражениях (англ)](https://blogs.msdn.microsoft.com/drew/2009/12/31/a-simple-lexer-in-c-that-uses-regular-expressions/)
[Пример библиотеки](https://github.com/b3b00/csly)

**Comment by Lacerta98** [comment]
[Dokument_Microsoft_Word.docx](https://github.com/Students-of-the-city-of-Kostroma/16PIa/files/1993058/Dokument_Microsoft_Word.docx)
