### ISSUE TITLE
Тестировщикам: разобраться в механизме юнит-тестирования Visual Studio

### ISSUE THREAD

**Issue by the-vindicar** [Students-of-the-city-of-Kostroma/16PIa#2]
[Юнит-тестирование](https://docs.microsoft.com/ru-ru/visualstudio/test/unit-test-basics)

**Comment by Lacerta98** [comment]
[Sozdaem_novy_proekt.docx](https://github.com/Students-of-the-city-of-Kostroma/16PIa/files/1993401/Sozdaem_novy_proekt.docx)
