### ISSUE TITLE
Набор тестов для библиотеки-лексера

### ISSUE THREAD

**Issue by the-vindicar** [Students-of-the-city-of-Kostroma/16PIa#3]
Придумать набор тестов, проверяющий граничные случаи при разборе строки.
Например:
* 2 - 2
* 2-2
* 2*-2
* -2-2
* 2 2 + 2
* и т.д.

**Comment by Lacerta98** [comment]
- 2 2+2
+2+ 2
22+--2
2.3e+04
04+03
titu3
2./*-+
/*-+
.23+5
,56+7,
